/**
 * Generates `firestore.rules` from `firestore.rules.template` by injecting the allowlisted UIDs.
 *
 *   npm run rules:build        → uses ALLOWED_UIDS from the environment / .env.local
 *   npm run rules:build:test   → uses the fixed test UIDs (alice, bob) for the emulator
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

export const TEST_UIDS = ["alice", "bob"] as const;
const PLACEHOLDER = "/*__ALLOWED_UIDS__*/";
const UID_PATTERN = /^[A-Za-z0-9_-]{1,128}$/;

const root = resolve(import.meta.dirname, "..");
const isTest = process.argv.includes("--test");

function loadEnv(): void {
  for (const file of [".env.local", ".env"]) {
    const path = resolve(root, file);
    if (existsSync(path)) process.loadEnvFile(path);
  }
}

function getUids(): string[] {
  if (isTest) return [...TEST_UIDS];
  loadEnv();
  const raw = process.env.ALLOWED_UIDS ?? "";
  const uids = raw
    .split(",")
    .map((s) => s.trim())
    .filter(Boolean);
  if (uids.length < 1 || uids.length > 2) {
    throw new Error(`ALLOWED_UIDS must contain 1–2 comma-separated UIDs (got ${uids.length}).`);
  }
  const bad = uids.find((u) => !UID_PATTERN.test(u));
  if (bad) throw new Error(`Invalid UID in ALLOWED_UIDS: "${bad}"`);
  return uids;
}

const template = readFileSync(resolve(root, "firestore.rules.template"), "utf8");
if (!template.includes(PLACEHOLDER)) throw new Error(`Template is missing ${PLACEHOLDER}`);

const uids = getUids();
const header = `// GENERATED by scripts/build-rules.mts (${isTest ? "TEST UIDs" : "production UIDs"}) — do not edit.\n`;
const rules = header + template.replace(PLACEHOLDER, uids.map((u) => `'${u}'`).join(", "));
writeFileSync(resolve(root, "firestore.rules"), rules);
console.log(`firestore.rules generated with ${uids.length} UID(s)${isTest ? " [test]" : ""}.`);
